import { OrganizationChart } from "./types"

export const INITIAL_ORG_CHARTS: OrganizationChart[] = [
  {
    id: "org-chart-mbmt-v4",
    title: "Organization Structure: TMBPL Project (MBMT)",
    chartType: "PROJECT_SITE",
    siteId: "cm-2",
    siteName: "Transvolt Mobility Private Limited",
    siteLocation: "Mira-Bhayandar (MBMT Transport Division)",
    version: "v4.0",
    status: "CURRENT",
    effectiveFrom: "2026-09-01",
    effectiveTo: undefined,
    createdAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-08T11:30:00Z",
    createdBy: "Faheem Shaikh (Super Admin)",
    updatedBy: "Faheem Shaikh (Super Admin)",
    changeSummary: "Updated OHS department and synced manpower requirements for Q3 2026.",
    canvasSettings: {
      zoom: 0.85,
      pan: { x: 80, y: 40 },
      gridSnap: true,
      gridVisible: true,
      printArea: "A3_LANDSCAPE",
      showPrintBounds: true,
    },
    boundaries: [
      {
        id: "bnd-ho",
        title: "HEAD OFFICE",
        position: { x: 120, y: 230 },
        width: 1380,
        height: 140,
        color: "#4472C4",
      },
      {
        id: "bnd-site",
        title: "PROJECT SITE (MBMT DEPOT)",
        position: { x: 40, y: 530 },
        width: 1540,
        height: 480,
        color: "#548235",
      },
    ],
    nodes: [
      // Level 1: CEO
      {
        id: "node-ceo",
        type: "EXECUTIVE",
        label: "Chief Executive Officer (CEO)",
        parentId: null,
        position: { x: 710, y: 30 },
        width: 220,
        height: 64,
        metadata: {
          designation: "Chief Executive Officer",
          department: "Executive Leadership",
          color: "#0F172A",
          bgColor: "#1E293B",
        },
      },
      // Level 2: BMO
      {
        id: "node-bmo",
        type: "MANAGEMENT",
        label: "Business Management Office (BMO)",
        parentId: "node-ceo",
        position: { x: 710, y: 130 },
        width: 220,
        height: 56,
        metadata: {
          designation: "Head - BMO",
          department: "Strategic Operations",
          color: "#1E3A8A",
          bgColor: "#2563EB",
        },
      },

      // Level 3: Head Office Directors (Inside HO Boundary)
      {
        id: "node-ho-em",
        type: "DEPARTMENT",
        label: "President E&M",
        parentId: "node-bmo",
        position: { x: 160, y: 260 },
        width: 180,
        height: 60,
        metadata: {
          designation: "President",
          department: "Engineering & Maintenance",
          color: "#2563EB",
        },
      },
      {
        id: "node-ho-cfo",
        type: "DEPARTMENT",
        label: "CFO",
        parentId: "node-bmo",
        position: { x: 380, y: 260 },
        width: 180,
        height: 60,
        metadata: {
          designation: "Chief Financial Officer",
          department: "Finance & Accounts",
          color: "#2563EB",
        },
      },
      {
        id: "node-ho-ops",
        type: "DEPARTMENT",
        label: "President Operations",
        parentId: "node-bmo",
        position: { x: 600, y: 260 },
        width: 200,
        height: 60,
        metadata: {
          designation: "President",
          department: "Operations",
          color: "#2563EB",
        },
      },
      {
        id: "node-ho-hr",
        type: "DEPARTMENT",
        label: "VP - HR",
        parentId: "node-bmo",
        position: { x: 840, y: 260 },
        width: 180,
        height: 60,
        metadata: {
          designation: "Vice President",
          department: "Human Resources",
          color: "#2563EB",
        },
      },
      {
        id: "node-ho-ohs",
        type: "DEPARTMENT",
        label: "VP - OHS",
        parentId: "node-bmo",
        position: { x: 1060, y: 260 },
        width: 180,
        height: 60,
        metadata: {
          designation: "Vice President",
          department: "Health, Safety & Environment",
          color: "#2563EB",
        },
      },
      {
        id: "node-ho-cto",
        type: "DEPARTMENT",
        label: "CTO",
        parentId: "node-bmo",
        position: { x: 1280, y: 260 },
        width: 180,
        height: 60,
        metadata: {
          designation: "Chief Technology Officer",
          department: "Technology & Software",
          color: "#2563EB",
        },
      },

      // Level 4: Project Manager
      {
        id: "node-pm",
        type: "MANAGEMENT",
        label: "Project Manager",
        parentId: "node-ho-ops",
        position: { x: 710, y: 410 },
        width: 220,
        height: 68,
        metadata: {
          name: "Vikram Singhania",
          designation: "Senior Project Manager",
          department: "MBMT Project",
          color: "#166534",
          bgColor: "#15803D",
        },
      },

      // Level 5: Site Departments
      // 1. Engineering & Maintenance
      {
        id: "node-dept-em",
        type: "DEPARTMENT",
        label: "Engineering & Maint.",
        parentId: "node-pm",
        position: { x: 60, y: 560 },
        width: 190,
        height: 52,
        metadata: { code: "EM-01", department: "Engineering & Maintenance", color: "#4472C4" },
      },
      {
        id: "node-emp-em1",
        type: "EMPLOYEE",
        label: "Rahul Sharma",
        parentId: "node-dept-em",
        position: { x: 60, y: 640 },
        width: 190,
        height: 64,
        metadata: {
          name: "Rahul Sharma",
          designation: "Service Engineer",
          employeeId: "TV-2024-012",
          employmentType: "EMPLOYEE",
        },
      },
      {
        id: "node-emp-em2",
        type: "EMPLOYEE",
        label: "Manoj Kulkarni",
        parentId: "node-dept-em",
        position: { x: 60, y: 724 },
        width: 190,
        height: 64,
        metadata: {
          name: "Manoj Kulkarni",
          designation: "Senior Technician",
          employeeId: "TV-2024-019",
          employmentType: "EMPLOYEE",
        },
      },
      {
        id: "node-req-em1",
        type: "REQUIRED_POSITION",
        label: "EV Charger Specialist",
        parentId: "node-dept-em",
        position: { x: 60, y: 808 },
        width: 190,
        height: 60,
        metadata: {
          designation: "EV Charger Specialist",
          requiredQuantity: 2,
          employmentType: "EMPLOYEE",
        },
      },

      // 2. Finance & Accounting
      {
        id: "node-dept-fa",
        type: "DEPARTMENT",
        label: "Finance & Accounting",
        parentId: "node-pm",
        position: { x: 275, y: 560 },
        width: 190,
        height: 52,
        metadata: { code: "FA-02", department: "Finance & Accounting", color: "#4472C4" },
      },
      {
        id: "node-emp-fa1",
        type: "EMPLOYEE",
        label: "Amit Trivedi",
        parentId: "node-dept-fa",
        position: { x: 275, y: 640 },
        width: 190,
        height: 64,
        metadata: {
          name: "Amit Trivedi",
          designation: "Finance & Accounts Manager",
          employeeId: "TV-2024-008",
          employmentType: "EMPLOYEE",
        },
      },
      {
        id: "node-cons-fa1",
        type: "CONSULTANT",
        label: "Priya Shah",
        parentId: "node-dept-fa",
        position: { x: 275, y: 724 },
        width: 190,
        height: 64,
        metadata: {
          name: "Priya Shah",
          designation: "Financial Audit Consultant",
          employeeId: "TV-CON-003",
          employmentType: "CONSULTANT",
        },
      },

      // 3. Operations
      {
        id: "node-dept-ops",
        type: "DEPARTMENT",
        label: "Operations",
        parentId: "node-pm",
        position: { x: 490, y: 560 },
        width: 200,
        height: 52,
        metadata: { code: "OPS-03", department: "Operations", color: "#4472C4" },
      },
      {
        id: "node-emp-ops1",
        type: "EMPLOYEE",
        label: "Rajesh Solanki",
        parentId: "node-dept-ops",
        position: { x: 490, y: 640 },
        width: 200,
        height: 64,
        metadata: {
          name: "Rajesh Solanki",
          designation: "Duty Supervisor",
          employeeId: "TV-2024-015",
          employmentType: "EMPLOYEE",
        },
      },
      {
        id: "node-emp-ops2",
        type: "EMPLOYEE",
        label: "Suresh Patil",
        parentId: "node-dept-ops",
        position: { x: 490, y: 724 },
        width: 200,
        height: 64,
        metadata: {
          name: "Suresh Patil",
          designation: "Lead Pilot / Trainer",
          employeeId: "TV-2024-022",
          employmentType: "EMPLOYEE",
        },
      },
      {
        id: "node-req-ops1",
        type: "REQUIRED_POSITION",
        label: "Electric Bus Pilots",
        parentId: "node-dept-ops",
        position: { x: 490, y: 808 },
        width: 200,
        height: 60,
        metadata: {
          designation: "Electric Bus Pilots",
          requiredQuantity: 5,
          employmentType: "EMPLOYEE",
        },
      },

      // 4. HR & Admin
      {
        id: "node-dept-hr",
        type: "DEPARTMENT",
        label: "HR & Admin",
        parentId: "node-pm",
        position: { x: 715, y: 560 },
        width: 190,
        height: 52,
        metadata: { code: "HR-04", department: "HR & Admin", color: "#4472C4" },
      },
      {
        id: "node-emp-hr1",
        type: "EMPLOYEE",
        label: "Deepa Nair",
        parentId: "node-dept-hr",
        position: { x: 715, y: 640 },
        width: 190,
        height: 64,
        metadata: {
          name: "Deepa Nair",
          designation: "HR & Admin Executive",
          employeeId: "TV-2024-025",
          employmentType: "EMPLOYEE",
        },
      },
      {
        id: "node-req-hr1",
        type: "REQUIRED_POSITION",
        label: "Admin Assistant",
        parentId: "node-dept-hr",
        position: { x: 715, y: 724 },
        width: 190,
        height: 60,
        metadata: {
          designation: "Admin Assistant",
          requiredQuantity: 1,
          employmentType: "EMPLOYEE",
        },
      },

      // 5. OHS
      {
        id: "node-dept-ohs",
        type: "DEPARTMENT",
        label: "OHS (Health & Safety)",
        parentId: "node-pm",
        position: { x: 930, y: 560 },
        width: 190,
        height: 52,
        metadata: { code: "OHS-05", department: "OHS", color: "#4472C4" },
      },
      {
        id: "node-emp-ohs1",
        type: "EMPLOYEE",
        label: "Vinod Pawar",
        parentId: "node-dept-ohs",
        position: { x: 930, y: 640 },
        width: 190,
        height: 64,
        metadata: {
          name: "Vinod Pawar",
          designation: "Safety & Compliance Officer",
          employeeId: "TV-2024-031",
          employmentType: "EMPLOYEE",
        },
      },

      // 6. IT
      {
        id: "node-dept-it",
        type: "DEPARTMENT",
        label: "IT & Telematics",
        parentId: "node-pm",
        position: { x: 1145, y: 560 },
        width: 190,
        height: 52,
        metadata: { code: "IT-06", department: "IT & Telematics", color: "#4472C4" },
      },
      {
        id: "node-emp-it1",
        type: "EMPLOYEE",
        label: "Sachin Deshmukh",
        parentId: "node-dept-it",
        position: { x: 1145, y: 640 },
        width: 190,
        height: 64,
        metadata: {
          name: "Sachin Deshmukh",
          designation: "MIS & Telematics Support",
          employeeId: "TV-2024-034",
          employmentType: "EMPLOYEE",
        },
      },

      // 7. Store
      {
        id: "node-dept-store",
        type: "DEPARTMENT",
        label: "Store & Spares",
        parentId: "node-pm",
        position: { x: 1360, y: 560 },
        width: 190,
        height: 52,
        metadata: { code: "ST-07", department: "Store", color: "#4472C4" },
      },
      {
        id: "node-emp-store1",
        type: "EMPLOYEE",
        label: "Ramesh Yadav",
        parentId: "node-dept-store",
        position: { x: 1360, y: 640 },
        width: 190,
        height: 64,
        metadata: {
          name: "Ramesh Yadav",
          designation: "Store Incharge",
          employeeId: "TV-2024-038",
          employmentType: "EMPLOYEE",
        },
      },
      {
        id: "node-emp-store2",
        type: "EMPLOYEE",
        label: "Santosh Shinde",
        parentId: "node-dept-store",
        position: { x: 1360, y: 724 },
        width: 190,
        height: 64,
        metadata: {
          name: "Santosh Shinde",
          designation: "Inventory Associate",
          employeeId: "TV-2024-041",
          employmentType: "EMPLOYEE",
        },
      },
    ],
    connections: [
      { id: "conn-1", source: "node-ceo", target: "node-bmo", type: "orthogonal" },
      { id: "conn-2", source: "node-bmo", target: "node-ho-em", type: "orthogonal" },
      { id: "conn-3", source: "node-bmo", target: "node-ho-cfo", type: "orthogonal" },
      { id: "conn-4", source: "node-bmo", target: "node-ho-ops", type: "orthogonal" },
      { id: "conn-5", source: "node-bmo", target: "node-ho-hr", type: "orthogonal" },
      { id: "conn-6", source: "node-bmo", target: "node-ho-ohs", type: "orthogonal" },
      { id: "conn-7", source: "node-bmo", target: "node-ho-cto", type: "orthogonal" },
      { id: "conn-8", source: "node-ho-ops", target: "node-pm", type: "orthogonal" },
      // PM to Departments
      { id: "conn-9", source: "node-pm", target: "node-dept-em", type: "orthogonal" },
      { id: "conn-10", source: "node-pm", target: "node-dept-fa", type: "orthogonal" },
      { id: "conn-11", source: "node-pm", target: "node-dept-ops", type: "orthogonal" },
      { id: "conn-12", source: "node-pm", target: "node-dept-hr", type: "orthogonal" },
      { id: "conn-13", source: "node-pm", target: "node-dept-ohs", type: "orthogonal" },
      { id: "conn-14", source: "node-pm", target: "node-dept-it", type: "orthogonal" },
      { id: "conn-15", source: "node-pm", target: "node-dept-store", type: "orthogonal" },
      // Dept to Employees
      { id: "conn-16", source: "node-dept-em", target: "node-emp-em1", type: "orthogonal" },
      { id: "conn-17", source: "node-emp-em1", target: "node-emp-em2", type: "orthogonal" },
      { id: "conn-18", source: "node-emp-em2", target: "node-req-em1", type: "orthogonal" },
      { id: "conn-19", source: "node-dept-fa", target: "node-emp-fa1", type: "orthogonal" },
      { id: "conn-20", source: "node-emp-fa1", target: "node-cons-fa1", type: "orthogonal" },
      { id: "conn-21", source: "node-dept-ops", target: "node-emp-ops1", type: "orthogonal" },
      { id: "conn-22", source: "node-emp-ops1", target: "node-emp-ops2", type: "orthogonal" },
      { id: "conn-23", source: "node-emp-ops2", target: "node-req-ops1", type: "orthogonal" },
      { id: "conn-24", source: "node-dept-hr", target: "node-emp-hr1", type: "orthogonal" },
      { id: "conn-25", source: "node-emp-hr1", target: "node-req-hr1", type: "orthogonal" },
      { id: "conn-26", source: "node-dept-ohs", target: "node-emp-ohs1", type: "orthogonal" },
      { id: "conn-27", source: "node-dept-it", target: "node-emp-it1", type: "orthogonal" },
      { id: "conn-28", source: "node-dept-store", target: "node-emp-store1", type: "orthogonal" },
      { id: "conn-29", source: "node-emp-store1", target: "node-emp-store2", type: "orthogonal" },
    ],
    footer: {
      enabled: true,
      projectInfo: {
        projectName: "Mira-Bhayandar Municipal Corporation (Transport Division)",
        projectLocation: "Mira-Bhayandar (Mumbai)",
        projectCode: "TMBPL-MBMT-2026",
        projectManager: "Vikram Singhania",
        effectiveDate: "01 September 2026",
      },
      manpowerColumns: [
        { id: "pilots", label: "Pilots" },
        { id: "onRoll", label: "Staff On Roll" },
        { id: "outsource", label: "Staff Outsource" },
      ],
      manpowerRows: [
        {
          key: "REQUIRED",
          label: "Required",
          values: { pilots: 60, onRoll: 18, outsource: 12 },
        },
        {
          key: "AVAILABLE",
          label: "Available",
          values: { pilots: 55, onRoll: 18, outsource: 11 },
        },
        {
          key: "GAP",
          label: "Gap",
          values: { pilots: -5, onRoll: 0, outsource: -1 },
        },
      ],
      vehicleMatrix: {
        vehicles: { required: 50, available: 45 },
        chargers: { required: 25, available: 25 },
      },
      legendItems: [
        { id: "leg-req", label: "Required", color: "#E11D48", indicator: "square" },
        { id: "leg-avl", label: "Available", color: "#16A34A", indicator: "square" },
        { id: "leg-gap", label: "Gap / Shortfall", color: "#DC2626", indicator: "square" },
        { id: "leg-exec", label: "CEO & BMO", color: "#0F172A", indicator: "dot" },
        { id: "leg-dept", label: "Departments", color: "#2563EB", indicator: "square" },
        { id: "leg-emp", label: "● Employee", color: "#16A34A", indicator: "dot" },
        { id: "leg-cons", label: "● Consultant", color: "#9333EA", indicator: "dot" },
        { id: "leg-vac", label: "○ Required Position", color: "#EA580C", indicator: "ring" },
      ],
      customNotes:
        "Approved organization structure for MBMT Phase-II operations. Any modifications must be sanctioned by BMO.",
    },
  },
  {
    id: "org-chart-ho-v1",
    title: "Organization Structure: Corporate Head Office",
    chartType: "HEAD_OFFICE",
    siteId: "cm-1",
    siteName: "Transvolt Mobility Private Limited",
    siteLocation: "Mumbai HQ",
    version: "v1.2",
    status: "CURRENT",
    effectiveFrom: "2026-01-01",
    effectiveTo: undefined,
    createdAt: "2026-01-01T09:00:00Z",
    updatedAt: "2026-06-15T14:20:00Z",
    createdBy: "Faheem Shaikh (Super Admin)",
    updatedBy: "Faheem Shaikh (Super Admin)",
    changeSummary: "Added Corporate Sustainability Division.",
    canvasSettings: {
      zoom: 0.9,
      pan: { x: 100, y: 50 },
      gridSnap: true,
      gridVisible: true,
      printArea: "A3_LANDSCAPE",
      showPrintBounds: true,
    },
    boundaries: [
      {
        id: "bnd-corp",
        title: "CORPORATE HEADQUARTERS",
        position: { x: 100, y: 150 },
        width: 1200,
        height: 380,
        color: "#4472C4",
      },
    ],
    nodes: [
      {
        id: "ho-ceo",
        type: "EXECUTIVE",
        label: "Chief Executive Officer (CEO)",
        parentId: null,
        position: { x: 600, y: 40 },
        width: 220,
        height: 64,
        metadata: { designation: "CEO", department: "Executive Office" },
      },
      {
        id: "ho-cfo",
        type: "DEPARTMENT",
        label: "Finance & Accounts",
        parentId: "ho-ceo",
        position: { x: 150, y: 200 },
        width: 180,
        height: 52,
        metadata: { designation: "Chief Financial Officer" },
      },
      {
        id: "ho-ops",
        type: "DEPARTMENT",
        label: "Operations & Fleet",
        parentId: "ho-ceo",
        position: { x: 380, y: 200 },
        width: 180,
        height: 52,
        metadata: { designation: "President Operations" },
      },
      {
        id: "ho-tech",
        type: "DEPARTMENT",
        label: "Technology & Software",
        parentId: "ho-ceo",
        position: { x: 610, y: 200 },
        width: 180,
        height: 52,
        metadata: { designation: "Chief Technology Officer" },
      },
      {
        id: "ho-hr",
        type: "DEPARTMENT",
        label: "Human Resources",
        parentId: "ho-ceo",
        position: { x: 840, y: 200 },
        width: 180,
        height: 52,
        metadata: { designation: "VP Human Resources" },
      },
      {
        id: "ho-legal",
        type: "DEPARTMENT",
        label: "Legal & Regulatory",
        parentId: "ho-ceo",
        position: { x: 1070, y: 200 },
        width: 180,
        height: 52,
        metadata: { designation: "General Counsel" },
      },
    ],
    connections: [
      { id: "h-c1", source: "ho-ceo", target: "ho-cfo", type: "orthogonal" },
      { id: "h-c2", source: "ho-ceo", target: "ho-ops", type: "orthogonal" },
      { id: "h-c3", source: "ho-ceo", target: "ho-tech", type: "orthogonal" },
      { id: "h-c4", source: "ho-ceo", target: "ho-hr", type: "orthogonal" },
      { id: "h-c5", source: "ho-ceo", target: "ho-legal", type: "orthogonal" },
    ],
    footer: {
      enabled: true,
      projectInfo: {
        projectName: "Transvolt Corporate Headquarters",
        projectLocation: "Mumbai HQ",
        projectCode: "TMBPL-HQ-2026",
        projectManager: "Corporate Board",
        effectiveDate: "01 January 2026",
      },
      manpowerColumns: [
        { id: "corporate", label: "Corporate Staff" },
        { id: "consultants", label: "Specialist Advisors" },
      ],
      manpowerRows: [
        {
          key: "REQUIRED",
          label: "Required",
          values: { corporate: 45, consultants: 8 },
        },
        {
          key: "AVAILABLE",
          label: "Available",
          values: { corporate: 42, consultants: 8 },
        },
        {
          key: "GAP",
          label: "Gap",
          values: { corporate: -3, consultants: 0 },
        },
      ],
      vehicleMatrix: {
        vehicles: { required: 10, available: 10 },
        chargers: { required: 4, available: 4 },
      },
      legendItems: [
        { id: "l-exec", label: "Executive", color: "#0F172A", indicator: "dot" },
        { id: "l-dept", label: "Department", color: "#2563EB", indicator: "square" },
      ],
    },
  },
  {
    id: "org-chart-mbmt-v3-archived",
    title: "Organization Structure: TMBPL Project (MBMT) - Q2 2026",
    chartType: "PROJECT_SITE",
    siteId: "cm-2",
    siteName: "Transvolt Mobility Private Limited",
    siteLocation: "Mira-Bhayandar (MBMT Transport Division)",
    version: "v3.0",
    status: "ARCHIVED",
    effectiveFrom: "2026-04-01",
    effectiveTo: "2026-08-31",
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-04-01T08:00:00Z",
    createdBy: "Faheem Shaikh (Super Admin)",
    updatedBy: "Faheem Shaikh (Super Admin)",
    changeSummary: "Previous historical version before Phase-II expansion.",
    canvasSettings: {
      zoom: 0.85,
      pan: { x: 80, y: 40 },
      gridSnap: true,
      gridVisible: true,
      printArea: "A3_LANDSCAPE",
      showPrintBounds: true,
    },
    boundaries: [],
    nodes: [],
    connections: [],
    footer: {
      enabled: false,
      projectInfo: {
        projectName: "MBMT Project",
        projectLocation: "Mira-Bhayandar",
        projectCode: "TMBPL-MBMT",
        projectManager: "Vikram Singhania",
        effectiveDate: "01 April 2026",
      },
      manpowerColumns: [],
      manpowerRows: [],
      vehicleMatrix: { vehicles: { required: 40, available: 40 }, chargers: { required: 20, available: 20 } },
      legendItems: [],
    },
  },
]
