import { GraphicCategory, GraphicFile } from "./types"

export const DEFAULT_GRAPHIC_CATEGORIES: GraphicCategory[] = [
  {
    id: "cat-1",
    name: "Brand Marks & Vector Graphics",
    description: "Official Transvolt vector marks, emblems, icons, and scalable brand assets.",
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-09-01T12:00:00.000Z",
  },
  {
    id: "cat-2",
    name: "Vehicle Fleet & Decal Artwork",
    description: "Production-ready wrap vinyls, bus decals, truck side vector layouts.",
    createdAt: "2026-08-18T11:30:00.000Z",
    updatedAt: "2026-09-02T14:15:00.000Z",
  },
  {
    id: "cat-3",
    name: "Social Media & Digital Creatives",
    description: "Approved Instagram, LinkedIn, and Web campaign visuals and vector post creatives.",
    createdAt: "2026-08-20T09:00:00.000Z",
    updatedAt: "2026-09-05T16:40:00.000Z",
  },
  {
    id: "cat-4",
    name: "Event Banners & Exhibition Backdrops",
    description: "Large format flex banners, podium wraps, and conference backdrop artwork.",
    createdAt: "2026-08-25T14:20:00.000Z",
    updatedAt: "2026-09-08T10:10:00.000Z",
  },
  {
    id: "cat-5",
    name: "Corporate Marketing & Collaterals",
    description: "Brochures, pitch deck vector illustrations, fact-sheets, and flyers.",
    createdAt: "2026-08-28T08:45:00.000Z",
    updatedAt: "2026-09-10T15:30:00.000Z",
  },
]

export const DEFAULT_GRAPHIC_FILES: GraphicFile[] = [
  // Category 1: Brand Marks & Vector Graphics
  {
    id: "gf-101",
    categoryId: "cat-1",
    name: "Transvolt_Master_Emblem_PrintReady",
    originalFileName: "Transvolt_Master_Emblem_PrintReady.ai",
    format: "AI",
    fileSize: "4.2 MB",
    uploadedAt: "2026-08-15T10:30:00.000Z",
    status: "active",
    version: "v2.1",
  },
  {
    id: "gf-102",
    categoryId: "cat-1",
    name: "Transvolt_Horizontal_Lockup_CMYK",
    originalFileName: "Transvolt_Horizontal_Lockup_CMYK.cdr",
    format: "CDR",
    fileSize: "3.8 MB",
    uploadedAt: "2026-08-16T11:00:00.000Z",
    status: "active",
    version: "v1.0",
  },
  {
    id: "gf-103",
    categoryId: "cat-1",
    name: "Transvolt_Lightning_Bolt_Monogram",
    originalFileName: "Transvolt_Lightning_Bolt_Monogram.svg",
    format: "SVG",
    fileSize: "142 KB",
    uploadedAt: "2026-08-17T14:15:00.000Z",
    status: "active",
    version: "v1.2",
  },
  {
    id: "gf-104",
    categoryId: "cat-1",
    name: "Transvolt_Favicon_And_App_Icons",
    originalFileName: "Transvolt_Favicon_And_App_Icons.png",
    format: "PNG",
    fileSize: "850 KB",
    uploadedAt: "2026-08-18T16:00:00.000Z",
    status: "active",
    version: "v1.0",
  },

  // Category 2: Vehicle Fleet & Decal Artwork
  {
    id: "gf-201",
    categoryId: "cat-2",
    name: "Commercial_Bus_FullWrap_Vector_Scale1-10",
    originalFileName: "Commercial_Bus_FullWrap_Vector_Scale1-10.ai",
    format: "AI",
    fileSize: "18.6 MB",
    uploadedAt: "2026-08-19T13:45:00.000Z",
    status: "active",
    version: "v3.0",
  },
  {
    id: "gf-202",
    categoryId: "cat-2",
    name: "Fleet_Rear_Safety_Warning_Decal_Template",
    originalFileName: "Fleet_Rear_Safety_Warning_Decal_Template.cdr",
    format: "CDR",
    fileSize: "2.4 MB",
    uploadedAt: "2026-08-20T10:15:00.000Z",
    status: "active",
    version: "v1.0",
  },
  {
    id: "gf-203",
    categoryId: "cat-2",
    name: "EV_Van_Door_Branding_Plotter_Cut",
    originalFileName: "EV_Van_Door_Branding_Plotter_Cut.pdf",
    format: "PDF",
    fileSize: "5.1 MB",
    uploadedAt: "2026-08-22T17:30:00.000Z",
    status: "hold",
    version: "v1.1",
  },

  // Category 3: Social Media & Digital Creatives
  {
    id: "gf-301",
    categoryId: "cat-3",
    name: "Green_Mobility_Milestone_Square_Post",
    originalFileName: "Green_Mobility_Milestone_Square_Post.png",
    format: "PNG",
    fileSize: "1.9 MB",
    uploadedAt: "2026-08-25T11:20:00.000Z",
    status: "active",
    version: "v1.0",
  },
  {
    id: "gf-302",
    categoryId: "cat-3",
    name: "Clean_Energy_Summit_Story_Graphic",
    originalFileName: "Clean_Energy_Summit_Story_Graphic.jpg",
    format: "JPG",
    fileSize: "920 KB",
    uploadedAt: "2026-08-26T15:10:00.000Z",
    status: "active",
    version: "v1.0",
  },
  {
    id: "gf-303",
    categoryId: "cat-3",
    name: "Carousel_Slide_Deck_Template_1080x1350",
    originalFileName: "Carousel_Slide_Deck_Template_1080x1350.ppt",
    format: "PPT",
    fileSize: "7.4 MB",
    uploadedAt: "2026-08-27T18:40:00.000Z",
    status: "active",
    version: "v2.0",
  },

  // Category 4: Event Banners & Exhibition Backdrops
  {
    id: "gf-401",
    categoryId: "cat-4",
    name: "AutoExpo_Main_Exhibition_Backdrop_12x8ft",
    originalFileName: "AutoExpo_Main_Exhibition_Backdrop_12x8ft.cdr",
    format: "CDR",
    fileSize: "32.4 MB",
    uploadedAt: "2026-08-29T10:00:00.000Z",
    status: "active",
    version: "v1.0",
  },
  {
    id: "gf-402",
    categoryId: "cat-4",
    name: "Rollup_Standee_Sustainable_Logistics",
    originalFileName: "Rollup_Standee_Sustainable_Logistics.pdf",
    format: "PDF",
    fileSize: "12.8 MB",
    uploadedAt: "2026-08-30T14:30:00.000Z",
    status: "active",
    version: "v1.3",
  },

  // Category 5: Corporate Marketing & Collaterals
  {
    id: "gf-501",
    categoryId: "cat-5",
    name: "Transvolt_Corporate_Profile_Vector_Kit",
    originalFileName: "Transvolt_Corporate_Profile_Vector_Kit.ai",
    format: "AI",
    fileSize: "14.1 MB",
    uploadedAt: "2026-09-02T12:00:00.000Z",
    status: "active",
    version: "v1.0",
  },
  {
    id: "gf-502",
    categoryId: "cat-5",
    name: "Investor_Briefing_Deck_Master_Vector_Assets",
    originalFileName: "Investor_Briefing_Deck_Master_Vector_Assets.ppt",
    format: "PPT",
    fileSize: "9.5 MB",
    uploadedAt: "2026-09-04T16:25:00.000Z",
    status: "hold",
    version: "v2.0",
  },
]
