import { CanvasObject } from "@/types/eva-editor"

export function buildLandingPageHero(baseX: number = 180, baseY: number = 140): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Glassmorphism Hero Container
    {
      id: `hero-bg-${ts}`,
      name: "Hero Container (Glass)",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 720,
      height: 440,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#334155",
      strokeWidth: 1.5,
      cornerRadius: 24,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.4)",
      shadowBlur: 28,
      shadowOffsetX: 0,
      shadowOffsetY: 14,
      zIndex: 1,
    },
    // 2. Micro Badge Pill
    {
      id: `hero-badge-${ts}`,
      name: "Brand Announcement Badge",
      type: "rectangle",
      x: baseX + 40,
      y: baseY + 36,
      width: 280,
      height: 32,
      rotation: 0,
      opacity: 1,
      fill: "rgba(84, 130, 53, 0.18)",
      stroke: "#548235",
      strokeWidth: 1,
      cornerRadius: 999,
      blendMode: "normal",
      zIndex: 2,
    },
    {
      id: `hero-badge-txt-${ts}`,
      name: "Badge Text",
      type: "text",
      x: baseX + 50,
      y: baseY + 42,
      width: 260,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#86efac",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡ NEXT-GEN EV TRANSIT FLEET",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 3,
    },
    // 3. Hero Main Headline
    {
      id: `hero-title-${ts}`,
      name: "Hero Display Title",
      type: "text",
      x: baseX + 40,
      y: baseY + 86,
      width: 430,
      height: 100,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Powering India's\nSustainable EV Future",
      fontSize: 32,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.15,
      zIndex: 4,
    },
    // 4. Hero Subtitle
    {
      id: `hero-subtitle-${ts}`,
      name: "Hero Body Paragraph",
      type: "text",
      x: baseX + 40,
      y: baseY + 200,
      width: 410,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Intelligent telemetry, automated depot charging grids, and turnkey electric bus fleet operations with 99.2% uptime guarantee.",
      fontSize: 13,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.45,
      zIndex: 5,
    },
    // 5. Primary CTA Button
    {
      id: `hero-cta-pri-${ts}`,
      name: "Primary CTA Button",
      type: "rectangle",
      x: baseX + 40,
      y: baseY + 290,
      width: 175,
      height: 46,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#44692b",
      strokeWidth: 1,
      cornerRadius: 12,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(84, 130, 53, 0.4)",
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 6,
      zIndex: 6,
    },
    {
      id: `hero-cta-pri-txt-${ts}`,
      name: "Primary CTA Text",
      type: "text",
      x: baseX + 45,
      y: baseY + 304,
      width: 165,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Explore Fleet →",
      fontSize: 13,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 7,
    },
    // 6. Secondary CTA Button
    {
      id: `hero-cta-sec-${ts}`,
      name: "Secondary CTA Button",
      type: "rectangle",
      x: baseX + 230,
      y: baseY + 290,
      width: 155,
      height: 46,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#475569",
      strokeWidth: 1.5,
      cornerRadius: 12,
      blendMode: "normal",
      zIndex: 8,
    },
    {
      id: `hero-cta-sec-txt-${ts}`,
      name: "Secondary CTA Text",
      type: "text",
      x: baseX + 235,
      y: baseY + 304,
      width: 145,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#e2e8f0",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Book Depot Tour",
      fontSize: 13,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 9,
    },
    // 7. Right Feature Metric Card (Glass)
    {
      id: `hero-preview-${ts}`,
      name: "Metric Preview Card",
      type: "rectangle",
      x: baseX + 490,
      y: baseY + 70,
      width: 195,
      height: 290,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#3b82f6",
      strokeWidth: 1.5,
      cornerRadius: 18,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(59, 130, 246, 0.2)",
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 8,
      zIndex: 10,
    },
    {
      id: `hero-preview-stat-${ts}`,
      name: "Preview Stat Value",
      type: "text",
      x: baseX + 505,
      y: baseY + 95,
      width: 165,
      height: 36,
      rotation: 0,
      opacity: 1,
      fill: "#38bdf8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "+99.2%",
      fontSize: 26,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 11,
    },
    {
      id: `hero-preview-lbl-${ts}`,
      name: "Preview Stat Label",
      type: "text",
      x: baseX + 500,
      y: baseY + 135,
      width: 175,
      height: 40,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Real-Time Fleet Uptime across 12 Depot Hubs",
      fontSize: 11,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 12,
    },
    // Sparkline Path
    {
      id: `hero-sparkline-${ts}`,
      name: "Uptime Sparkline",
      type: "path",
      x: baseX + 510,
      y: baseY + 200,
      width: 155,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#10b981",
      strokeWidth: 3,
      blendMode: "normal",
      pathData: "M 0 50 Q 30 20 60 35 T 120 15 T 150 5",
      zIndex: 13,
    },
  ]
}

export function buildHouseBlueprint(baseX: number = 160, baseY: number = 100): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Foundation Blueprint Plate
    {
      id: `bp-plate-${ts}`,
      name: "Blueprint Plate (2400 Sq.Ft)",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 720,
      height: 480,
      rotation: 0,
      opacity: 1,
      fill: "#091729",
      stroke: "#1d4ed8",
      strokeWidth: 3,
      cornerRadius: 6,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.5)",
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // 2. Blueprint Header
    {
      id: `bp-hdr-${ts}`,
      name: "Blueprint Header Legend",
      type: "text",
      x: baseX + 24,
      y: baseY + 18,
      width: 670,
      height: 28,
      rotation: 0,
      opacity: 1,
      fill: "#93c5fd",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "ARCHITECTURAL BLUEPRINT · ECO-VILLA TRANSVOLT · SCALE: 1/4\" = 1'-0\" · REV 4.2",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Courier New, monospace",
      textAlign: "left",
      zIndex: 2,
    },
    // 3. Structural Outer Wall
    {
      id: `bp-outer-wall-${ts}`,
      name: "Load-Bearing Outer Wall",
      type: "rectangle",
      x: baseX + 40,
      y: baseY + 55,
      width: 640,
      height: 380,
      rotation: 0,
      opacity: 1,
      fill: "rgba(30, 58, 138, 0.25)",
      stroke: "#60a5fa",
      strokeWidth: 4,
      cornerRadius: 0,
      blendMode: "normal",
      zIndex: 3,
    },
    // 4. Living Room Partition
    {
      id: `bp-living-${ts}`,
      name: "Living Room (22' × 18')",
      type: "rectangle",
      x: baseX + 50,
      y: baseY + 65,
      width: 340,
      height: 220,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#3b82f6",
      strokeWidth: 2,
      cornerRadius: 0,
      blendMode: "normal",
      zIndex: 4,
    },
    {
      id: `bp-living-lbl-${ts}`,
      name: "Living Room Label",
      type: "text",
      x: baseX + 60,
      y: baseY + 160,
      width: 320,
      height: 40,
      rotation: 0,
      opacity: 1,
      fill: "#bfdbfe",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "GREAT LIVING ROOM\n22'-0\" × 18'-0\" · Hardwood Finish",
      fontSize: 12,
      fontWeight: "700",
      fontFamily: "Courier New, monospace",
      textAlign: "center",
      zIndex: 5,
    },
    // 5. Master Suite Partition
    {
      id: `bp-master-${ts}`,
      name: "Master Suite (16' × 14')",
      type: "rectangle",
      x: baseX + 400,
      y: baseY + 65,
      width: 270,
      height: 180,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#3b82f6",
      strokeWidth: 2,
      cornerRadius: 0,
      blendMode: "normal",
      zIndex: 6,
    },
    {
      id: `bp-master-lbl-${ts}`,
      name: "Master Suite Label",
      type: "text",
      x: baseX + 410,
      y: baseY + 140,
      width: 250,
      height: 40,
      rotation: 0,
      opacity: 1,
      fill: "#bfdbfe",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "MASTER BEDROOM\n16'-0\" × 14'-0\" · Attached Bath",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Courier New, monospace",
      textAlign: "center",
      zIndex: 7,
    },
    // 6. Modular Kitchen & Dining
    {
      id: `bp-kitchen-${ts}`,
      name: "Modular Kitchen & Dining",
      type: "rectangle",
      x: baseX + 50,
      y: baseY + 295,
      width: 340,
      height: 130,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#3b82f6",
      strokeWidth: 2,
      cornerRadius: 0,
      blendMode: "normal",
      zIndex: 8,
    },
    {
      id: `bp-kitchen-lbl-${ts}`,
      name: "Kitchen Label",
      type: "text",
      x: baseX + 60,
      y: baseY + 345,
      width: 320,
      height: 35,
      rotation: 0,
      opacity: 1,
      fill: "#bfdbfe",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "KITCHEN & DINING AISLE · 18'-0\" × 11'-0\"",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Courier New, monospace",
      textAlign: "center",
      zIndex: 9,
    },
    // 7. Balcony / Green Terrace
    {
      id: `bp-deck-${ts}`,
      name: "Solar Green Terrace",
      type: "rectangle",
      x: baseX + 400,
      y: baseY + 255,
      width: 270,
      height: 170,
      rotation: 0,
      opacity: 1,
      fill: "rgba(16, 185, 129, 0.12)",
      stroke: "#10b981",
      strokeWidth: 2,
      strokeDashArray: "6 4",
      cornerRadius: 0,
      blendMode: "normal",
      zIndex: 10,
    },
    {
      id: `bp-deck-lbl-${ts}`,
      name: "Terrace Label",
      type: "text",
      x: baseX + 410,
      y: baseY + 325,
      width: 250,
      height: 35,
      rotation: 0,
      opacity: 1,
      fill: "#6ee7b7",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "OPEN SOLAR TERRACE DECK\nEV Charging Port · 18'-0\" × 13'-0\"",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Courier New, monospace",
      textAlign: "center",
      zIndex: 11,
    },
    // 8. Door Swing Vector Arc
    {
      id: `bp-door-arc-${ts}`,
      name: "Main Entrance Door Swing Arc",
      type: "path",
      x: baseX + 190,
      y: baseY + 270,
      width: 60,
      height: 60,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#f59e0b",
      strokeWidth: 2,
      strokeDashArray: "4 3",
      blendMode: "normal",
      pathData: "M 0 0 A 45 45 0 0 1 45 45 L 0 45 Z",
      zIndex: 12,
    },
  ]
}

export function buildCheckoutScreen(baseX: number = 200, baseY: number = 100): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Checkout Card Base
    {
      id: `chk-base-${ts}`,
      name: "Checkout Container",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 580,
      height: 520,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#e2e8f0",
      strokeWidth: 1.5,
      cornerRadius: 20,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.12)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 8,
      zIndex: 1,
    },
    // 2. Checkout Header
    {
      id: `chk-hdr-${ts}`,
      name: "Checkout Header",
      type: "text",
      x: baseX + 32,
      y: baseY + 28,
      width: 516,
      height: 32,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Checkout & Order Summary",
      fontSize: 20,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 2,
    },
    // 3. Product Summary Box
    {
      id: `chk-prod-box-${ts}`,
      name: "Product Summary Card",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 70,
      width: 516,
      height: 72,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#cbd5e1",
      strokeWidth: 1,
      cornerRadius: 12,
      blendMode: "normal",
      zIndex: 3,
    },
    {
      id: `chk-prod-txt-${ts}`,
      name: "Product Details Text",
      type: "text",
      x: baseX + 48,
      y: baseY + 86,
      width: 480,
      height: 40,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡ Transvolt DC Fast Charger 120kW (Commercial Depot Edition)\nQty: 1 Unit · 3-Year Enterprise Fleet Warranty · ₹1,24,999",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.4,
      zIndex: 4,
    },
    // 4. Price Breakdown
    {
      id: `chk-breakdown-${ts}`,
      name: "Price Calculation",
      type: "text",
      x: baseX + 32,
      y: baseY + 160,
      width: 516,
      height: 60,
      rotation: 0,
      opacity: 1,
      fill: "#64748b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Subtotal: ₹1,24,999.00    |    GST (18%): ₹22,500.00    |    Depot Shipping: FREE",
      fontSize: 12,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 5,
    },
    // 5. Total Payable Highlight Pill
    {
      id: `chk-total-box-${ts}`,
      name: "Total Amount Bar",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 220,
      width: 516,
      height: 46,
      rotation: 0,
      opacity: 1,
      fill: "rgba(84, 130, 53, 0.1)",
      stroke: "#548235",
      strokeWidth: 1.5,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 6,
    },
    {
      id: `chk-total-txt-${ts}`,
      name: "Total Payable Text",
      type: "text",
      x: baseX + 48,
      y: baseY + 233,
      width: 480,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#2e5318",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Total Amount Due: ₹1,47,499.00 (Incl. Taxes)",
      fontSize: 14,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 7,
    },
    // 6. Payment Method Pills
    {
      id: `chk-pay-opt1-${ts}`,
      name: "Payment Method: Card",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 285,
      width: 160,
      height: 44,
      rotation: 0,
      opacity: 1,
      fill: "#f1f5f9",
      stroke: "#0070f3",
      strokeWidth: 2,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 8,
    },
    {
      id: `chk-pay-opt1-txt-${ts}`,
      name: "Method 1 Text",
      type: "text",
      x: baseX + 40,
      y: baseY + 298,
      width: 144,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#0070f3",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "💳 Credit / Debit Card",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 9,
    },
    {
      id: `chk-pay-opt2-${ts}`,
      name: "Payment Method: UPI",
      type: "rectangle",
      x: baseX + 210,
      y: baseY + 285,
      width: 160,
      height: 44,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#cbd5e1",
      strokeWidth: 1,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 10,
    },
    {
      id: `chk-pay-opt2-txt-${ts}`,
      name: "Method 2 Text",
      type: "text",
      x: baseX + 218,
      y: baseY + 298,
      width: 144,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#475569",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡ UPI / NetBanking",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 11,
    },
    {
      id: `chk-pay-opt3-${ts}`,
      name: "Payment Method: PO",
      type: "rectangle",
      x: baseX + 388,
      y: baseY + 285,
      width: 160,
      height: 44,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#cbd5e1",
      strokeWidth: 1,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 12,
    },
    {
      id: `chk-pay-opt3-txt-${ts}`,
      name: "Method 3 Text",
      type: "text",
      x: baseX + 396,
      y: baseY + 298,
      width: 144,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#475569",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "🏢 Corporate PO",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 13,
    },
    // 7. Coupon Input Field
    {
      id: `chk-coupon-box-${ts}`,
      name: "Coupon Code Input",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 350,
      width: 516,
      height: 42,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#cbd5e1",
      strokeWidth: 1,
      cornerRadius: 8,
      blendMode: "normal",
      zIndex: 14,
    },
    {
      id: `chk-coupon-txt-${ts}`,
      name: "Coupon Text",
      type: "text",
      x: baseX + 48,
      y: baseY + 362,
      width: 480,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#64748b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Promo: TRANSVOLT2026 Applied (10% Fleet Credit Claimed)",
      fontSize: 11,
      fontWeight: "500",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 15,
    },
    // 8. Primary Pay CTA
    {
      id: `chk-pay-btn-${ts}`,
      name: "Primary Pay CTA Button",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 412,
      width: 516,
      height: 52,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#44692b",
      strokeWidth: 1,
      cornerRadius: 12,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(84, 130, 53, 0.35)",
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 6,
      zIndex: 16,
    },
    {
      id: `chk-pay-btn-txt-${ts}`,
      name: "Primary Pay CTA Text",
      type: "text",
      x: baseX + 48,
      y: baseY + 427,
      width: 480,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Pay Securely ₹1,47,499.00 🔒",
      fontSize: 14,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 17,
    },
    // 9. Trust Badge
    {
      id: `chk-trust-${ts}`,
      name: "Trust & Security Badge",
      type: "text",
      x: baseX + 32,
      y: baseY + 478,
      width: 516,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "🔒 256-Bit SSL Encrypted  ·  RBI Authorized  ·  PCI-DSS Compliant Gateway",
      fontSize: 10,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 18,
    },
  ]
}

export function buildModernATSResume(baseX: number = 190, baseY: number = 60): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. A4 Document Sheet (595 x 842 pt equivalent)
    {
      id: `res-sheet-${ts}`,
      name: "ATS Resume A4 Sheet",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 620,
      height: 800,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#cbd5e1",
      strokeWidth: 1,
      cornerRadius: 4,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.15)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // 2. Executive Header Container
    {
      id: `res-hdr-box-${ts}`,
      name: "Header Banner",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 620,
      height: 120,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#0f172a",
      strokeWidth: 0,
      cornerRadius: 0,
      blendMode: "normal",
      zIndex: 2,
    },
    {
      id: `res-name-${ts}`,
      name: "Candidate Full Name",
      type: "text",
      x: baseX + 36,
      y: baseY + 20,
      width: 548,
      height: 36,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "ARJUN SHARMA",
      fontSize: 24,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 3,
    },
    {
      id: `res-title-${ts}`,
      name: "Candidate Professional Title",
      type: "text",
      x: baseX + 36,
      y: baseY + 58,
      width: 548,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Lead Systems & EV Mobility Architect  |  10+ Years Experience",
      fontSize: 13,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 4,
    },
    {
      id: `res-contact-${ts}`,
      name: "Contact Information Pill",
      type: "text",
      x: baseX + 36,
      y: baseY + 86,
      width: 548,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "✉ arjun@transvolt.in   |   ✆ +91 98765 43210   |   📍 Bengaluru, India   |   🔗 linkedin.com/in/arjun-ev",
      fontSize: 10,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 5,
    },
    // 3. Left Sidebar Column (Skills & Credentials)
    {
      id: `res-left-col-${ts}`,
      name: "Left Column Container",
      type: "rectangle",
      x: baseX + 24,
      y: baseY + 140,
      width: 190,
      height: 630,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#e2e8f0",
      strokeWidth: 1,
      cornerRadius: 8,
      blendMode: "normal",
      zIndex: 6,
    },
    {
      id: `res-skills-hdr-${ts}`,
      name: "Core Skills Heading",
      type: "text",
      x: baseX + 36,
      y: baseY + 155,
      width: 166,
      height: 22,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "CORE SKILLS",
      fontSize: 12,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 7,
    },
    {
      id: `res-skills-list-${ts}`,
      name: "Skills List",
      type: "text",
      x: baseX + 36,
      y: baseY + 182,
      width: 166,
      height: 180,
      rotation: 0,
      opacity: 1,
      fill: "#334155",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "• High Voltage (HV) Powertrain\n• Battery Management (BMS)\n• CAN Bus & Telematics\n• AutoCAD & SolidWorks\n• DC Fast Charging Grids\n• Thermal Runaway Safety\n• ISO 26262 Functional Safety\n• Fleet Optimization Algorithms",
      fontSize: 10,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.6,
      zIndex: 8,
    },
    {
      id: `res-edu-hdr-${ts}`,
      name: "Education Heading",
      type: "text",
      x: baseX + 36,
      y: baseY + 380,
      width: 166,
      height: 22,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "EDUCATION",
      fontSize: 12,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 9,
    },
    {
      id: `res-edu-list-${ts}`,
      name: "Education List",
      type: "text",
      x: baseX + 36,
      y: baseY + 405,
      width: 166,
      height: 100,
      rotation: 0,
      opacity: 1,
      fill: "#334155",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "M.Tech in Automotive Systems\nIIT Madras (2014 - 2016)\n\nB.Tech in Electrical Eng.\nNIT Trichy (2010 - 2014)",
      fontSize: 10,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.5,
      zIndex: 10,
    },
    // 4. Right Main Column (Professional Experience & Projects)
    {
      id: `res-exp-hdr-${ts}`,
      name: "Experience Heading",
      type: "text",
      x: baseX + 230,
      y: baseY + 140,
      width: 366,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "PROFESSIONAL EXPERIENCE",
      fontSize: 13,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 11,
    },
    {
      id: `res-job1-${ts}`,
      name: "Experience Role 1",
      type: "text",
      x: baseX + 230,
      y: baseY + 170,
      width: 366,
      height: 180,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Principal EV Architect  |  Transvolt Mobility\n2022 - Present  ·  Bengaluru, India\n\n• Architected heavy-duty 350kWh LFP battery enclosures for commercial electric transit buses.\n• Reduced battery thermal degradation by 24% via custom liquid cooling manifolds.\n• Spearheaded 120kW depot DC fast-charging deployment across 18 municipal transport hubs.",
      fontSize: 11,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.45,
      zIndex: 12,
    },
    {
      id: `res-job2-${ts}`,
      name: "Experience Role 2",
      type: "text",
      x: baseX + 230,
      y: baseY + 360,
      width: 366,
      height: 170,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Senior Powertrain Designer  |  Tata Technologies\n2017 - 2022  ·  Pune, India\n\n• Engineered regenerative braking control loops, increasing vehicle range by 14% on urban stop-and-go duty cycles.\n• Directed failure-mode-and-effects analysis (FMEA) ensuring 100% AIS-038 Rev 2 safety compliance.",
      fontSize: 11,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.45,
      zIndex: 13,
    },
    {
      id: `res-projects-hdr-${ts}`,
      name: "Projects Heading",
      type: "text",
      x: baseX + 230,
      y: baseY + 540,
      width: 366,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "PATENTS & KEY DELIVERABLES",
      fontSize: 13,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 14,
    },
    {
      id: `res-projects-txt-${ts}`,
      name: "Projects Text",
      type: "text",
      x: baseX + 230,
      y: baseY + 570,
      width: 366,
      height: 120,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "• Patent: Adaptive BMS Voltage Equalizer (Indian Patent Application 2024410198)\n• Delivered 1,200+ operating electric bus drivetrains across 4 Tier-1 transit authorities.\n• Recipient of National EV Innovation Award 2023.",
      fontSize: 11,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "left",
      lineHeight: 1.45,
      zIndex: 15,
    },
  ]
}

export function buildGreetingCard(baseX: number = 220, baseY: number = 100): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Royal Emerald Card Body
    {
      id: `gc-base-${ts}`,
      name: "Greeting Card Base",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 520,
      height: 480,
      rotation: 0,
      opacity: 1,
      fill: "#064e3b",
      stroke: "#047857",
      strokeWidth: 2,
      cornerRadius: 18,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.35)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // 2. Ornate Outer Gold Border
    {
      id: `gc-outer-border-${ts}`,
      name: "Ornate Gold Border",
      type: "rectangle",
      x: baseX + 20,
      y: baseY + 20,
      width: 480,
      height: 440,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#d97706",
      strokeWidth: 2,
      cornerRadius: 12,
      blendMode: "normal",
      zIndex: 2,
    },
    // 3. Inner Fine Gold Border
    {
      id: `gc-inner-border-${ts}`,
      name: "Inner Fine Border",
      type: "rectangle",
      x: baseX + 26,
      y: baseY + 26,
      width: 468,
      height: 428,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#fbbf24",
      strokeWidth: 0.8,
      strokeDashArray: "6 4",
      cornerRadius: 8,
      blendMode: "normal",
      zIndex: 3,
    },
    // 4. Central Festive Emblem Motif
    {
      id: `gc-star-${ts}`,
      name: "Gold Star Motif",
      type: "shape",
      subtype: "star",
      x: baseX + 235,
      y: baseY + 50,
      width: 50,
      height: 50,
      rotation: 0,
      opacity: 1,
      fill: "#fbbf24",
      stroke: "#d97706",
      strokeWidth: 1.5,
      blendMode: "normal",
      zIndex: 4,
    },
    // 5. Card Main Headline
    {
      id: `gc-title-${ts}`,
      name: "Celebratory Headline",
      type: "text",
      x: baseX + 40,
      y: baseY + 120,
      width: 440,
      height: 50,
      rotation: 0,
      opacity: 1,
      fill: "#fde68a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Warmest Greetings & Best Wishes",
      fontSize: 22,
      fontWeight: "700",
      fontFamily: "Georgia, serif",
      textAlign: "center",
      zIndex: 5,
    },
    // 6. Decorative Divider Line
    {
      id: `gc-divider-${ts}`,
      name: "Flourish Divider Line",
      type: "shape",
      subtype: "line",
      x: baseX + 135,
      y: baseY + 180,
      width: 250,
      height: 2,
      rotation: 0,
      opacity: 1,
      fill: "#d97706",
      stroke: "#fbbf24",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 6,
    },
    // 7. Festive Heartfelt Message
    {
      id: `gc-body-${ts}`,
      name: "Card Message Body",
      type: "text",
      x: baseX + 50,
      y: baseY + 205,
      width: 420,
      height: 120,
      rotation: 0,
      opacity: 1,
      fill: "#ecfdf5",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "May this joyful season bring abundant prosperity, health, and clean energy milestones to you and your loved ones. Thank you for partnering with us toward a zero-emission future.",
      fontSize: 13,
      fontWeight: "normal",
      fontFamily: "Georgia, serif",
      textAlign: "center",
      lineHeight: 1.6,
      zIndex: 7,
    },
    // 8. Sign-off Footer
    {
      id: `gc-signoff-${ts}`,
      name: "Signoff Footer",
      type: "text",
      x: baseX + 40,
      y: baseY + 360,
      width: 440,
      height: 50,
      rotation: 0,
      opacity: 1,
      fill: "#fef08a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "With warm regards,\nTHE TRANSVOLT MOBILITY TEAM",
      fontSize: 12,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      lineHeight: 1.4,
      zIndex: 8,
    },
  ]
}

export function buildFintechDashboardCard(baseX: number = 220, baseY: number = 130): CanvasObject[] {
  const ts = Date.now()
  return [
    {
      id: `fin-card-${ts}`,
      name: "Fintech Dashboard Container",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 520,
      height: 380,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#1e293b",
      strokeWidth: 1.5,
      cornerRadius: 20,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.4)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    {
      id: `fin-lbl-${ts}`,
      name: "Portfolio Label",
      type: "text",
      x: baseX + 32,
      y: baseY + 28,
      width: 456,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "TRANSVOLT FLEET CORPORATE TREASURY",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: `fin-bal-${ts}`,
      name: "Balance Display",
      type: "text",
      x: baseX + 32,
      y: baseY + 55,
      width: 456,
      height: 48,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "₹24,85,620.00",
      fontSize: 32,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 3,
    },
    // Growth Pill
    {
      id: `fin-growth-pill-${ts}`,
      name: "Growth Pill",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 115,
      width: 155,
      height: 28,
      rotation: 0,
      opacity: 1,
      fill: "rgba(16, 185, 129, 0.15)",
      stroke: "#10b981",
      strokeWidth: 1,
      cornerRadius: 999,
      blendMode: "normal",
      zIndex: 4,
    },
    {
      id: `fin-growth-txt-${ts}`,
      name: "Growth Text",
      type: "text",
      x: baseX + 38,
      y: baseY + 122,
      width: 143,
      height: 18,
      rotation: 0,
      opacity: 1,
      fill: "#6ee7b7",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "▲ +18.4% This Month",
      fontSize: 10,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 5,
    },
    // Sparkline Graph Path
    {
      id: `fin-chart-${ts}`,
      name: "Growth Curve",
      type: "path",
      x: baseX + 32,
      y: baseY + 160,
      width: 456,
      height: 80,
      rotation: 0,
      opacity: 1,
      fill: "transparent",
      stroke: "#10b981",
      strokeWidth: 3,
      blendMode: "normal",
      pathData: "M 0 65 Q 90 20 180 40 T 360 15 T 450 5",
      zIndex: 6,
    },
    // Fleet Card Line
    {
      id: `fin-card-num-${ts}`,
      name: "Masked Card Number",
      type: "text",
      x: baseX + 32,
      y: baseY + 265,
      width: 456,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "💳 Corporate Fleet Card  ·  •••• •••• •••• 9924   EXP 09/29",
      fontSize: 12,
      fontWeight: "500",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 7,
    },
    // Action Pills
    {
      id: `fin-btn1-${ts}`,
      name: "Action Button: Add Funds",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 305,
      width: 135,
      height: 42,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#548235",
      strokeWidth: 1,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 8,
    },
    {
      id: `fin-btn1-txt-${ts}`,
      name: "Action 1 Text",
      type: "text",
      x: baseX + 38,
      y: baseY + 318,
      width: 123,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "+ Add Funds",
      fontSize: 12,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 9,
    },
    {
      id: `fin-btn2-${ts}`,
      name: "Action Button: Transfer",
      type: "rectangle",
      x: baseX + 180,
      y: baseY + 305,
      width: 135,
      height: 42,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#334155",
      strokeWidth: 1,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 10,
    },
    {
      id: `fin-btn2-txt-${ts}`,
      name: "Action 2 Text",
      type: "text",
      x: baseX + 186,
      y: baseY + 318,
      width: 123,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#e2e8f0",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⇄ Transfer",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 11,
    },
    {
      id: `fin-btn3-${ts}`,
      name: "Action Button: Charging Credits",
      type: "rectangle",
      x: baseX + 328,
      y: baseY + 305,
      width: 160,
      height: 42,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#334155",
      strokeWidth: 1,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 12,
    },
    {
      id: `fin-btn3-txt-${ts}`,
      name: "Action 3 Text",
      type: "text",
      x: baseX + 334,
      y: baseY + 318,
      width: 148,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#e2e8f0",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡ Charging Grids",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 13,
    },
  ]
}

export function buildVehicleBus(baseX: number = 180, baseY: number = 140): CanvasObject[] {
  const ts = Date.now()
  return [
    // Bus Chassis / Body Container
    {
      id: `bus-body-${ts}`,
      name: "Electric Bus Chassis",
      type: "rectangle",
      x: baseX,
      y: baseY + 50,
      width: 580,
      height: 180,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#548235",
      strokeWidth: 3,
      cornerRadius: 18,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(84, 130, 53, 0.35)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // Front Windshield
    {
      id: `bus-windshield-${ts}`,
      name: "Front Windshield",
      type: "rectangle",
      x: baseX + 450,
      y: baseY + 60,
      width: 110,
      height: 80,
      rotation: 0,
      opacity: 1,
      fill: "#38bdf8",
      stroke: "#0284c7",
      strokeWidth: 1.5,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 2,
    },
    // Passenger Panoramic Windows
    ...[0, 1, 2, 3].map((idx) => ({
      id: `bus-win-${idx}-${ts}`,
      name: `Passenger Window ${idx + 1}`,
      type: "rectangle" as const,
      x: baseX + 40 + idx * 95,
      y: baseY + 60,
      width: 80,
      height: 70,
      rotation: 0,
      opacity: 0.9,
      fill: "#0284c7",
      stroke: "#38bdf8",
      strokeWidth: 1,
      cornerRadius: 8,
      blendMode: "normal" as const,
      zIndex: 2,
    })),
    // Livery Branding Stripe
    {
      id: `bus-livery-${ts}`,
      name: "Transvolt Livery Stripe",
      type: "rectangle",
      x: baseX,
      y: baseY + 150,
      width: 580,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#548235",
      strokeWidth: 0,
      cornerRadius: 0,
      blendMode: "normal",
      zIndex: 3,
    },
    {
      id: `bus-logo-${ts}`,
      name: "Livery Typography",
      type: "text",
      x: baseX + 60,
      y: baseY + 153,
      width: 320,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡ TRANSVOLT 100% ELECTRIC TRANSIT",
      fontSize: 12,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 4,
    },
    // Front Headlight
    {
      id: `bus-headlight-${ts}`,
      name: "LED Matrix Headlight",
      type: "circle",
      x: baseX + 540,
      y: baseY + 180,
      width: 28,
      height: 28,
      rotation: 0,
      opacity: 1,
      fill: "#fde047",
      stroke: "#eab308",
      strokeWidth: 2,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "#fde047",
      shadowBlur: 14,
      shadowOffsetX: 4,
      shadowOffsetY: 0,
      zIndex: 4,
    },
    // Wheels (Front & Rear)
    {
      id: `bus-wheel-rear-${ts}`,
      name: "Rear Alloy Wheel",
      type: "circle",
      x: baseX + 90,
      y: baseY + 200,
      width: 70,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#64748b",
      strokeWidth: 4,
      blendMode: "normal",
      zIndex: 5,
    },
    {
      id: `bus-hub-rear-${ts}`,
      name: "Rear Hub Cap",
      type: "circle",
      x: baseX + 110,
      y: baseY + 220,
      width: 30,
      height: 30,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#ffffff",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 6,
    },
    {
      id: `bus-wheel-front-${ts}`,
      name: "Front Alloy Wheel",
      type: "circle",
      x: baseX + 430,
      y: baseY + 200,
      width: 70,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#64748b",
      strokeWidth: 4,
      blendMode: "normal",
      zIndex: 5,
    },
    {
      id: `bus-hub-front-${ts}`,
      name: "Front Hub Cap",
      type: "circle",
      x: baseX + 450,
      y: baseY + 220,
      width: 30,
      height: 30,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#ffffff",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 6,
    },
    // Underfloor Battery Pack Label
    {
      id: `bus-spec-${ts}`,
      name: "Battery Spec Annotation",
      type: "text",
      x: baseX + 180,
      y: baseY + 205,
      width: 230,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "350 kWh LFP Cell Pack · 280km Range",
      fontSize: 10,
      fontWeight: "600",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 6,
    },
  ]
}

export function buildLoginScreen(baseX: number = 240, baseY: number = 100): CanvasObject[] {
  const ts = Date.now()
  return [
    {
      id: `login-card-${ts}`,
      name: "Login Card Container",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 440,
      height: 480,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#e2e8f0",
      strokeWidth: 1.5,
      cornerRadius: 18,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.1)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    {
      id: `login-logo-pill-${ts}`,
      name: "Logo Accent Pill",
      type: "rectangle",
      x: baseX + 195,
      y: baseY + 32,
      width: 50,
      height: 50,
      rotation: 0,
      opacity: 1,
      fill: "rgba(84, 130, 53, 0.15)",
      stroke: "#548235",
      strokeWidth: 2,
      cornerRadius: 14,
      blendMode: "normal",
      zIndex: 2,
    },
    {
      id: `login-logo-txt-${ts}`,
      name: "Logo Icon",
      type: "text",
      x: baseX + 195,
      y: baseY + 42,
      width: 50,
      height: 30,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡",
      fontSize: 22,
      fontWeight: "700",
      textAlign: "center",
      zIndex: 3,
    },
    {
      id: `login-title-${ts}`,
      name: "Login Title",
      type: "text",
      x: baseX + 32,
      y: baseY + 96,
      width: 376,
      height: 32,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Welcome Back",
      fontSize: 22,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 3,
    },
    {
      id: `login-sub-${ts}`,
      name: "Login Subtitle",
      type: "text",
      x: baseX + 32,
      y: baseY + 130,
      width: 376,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#64748b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Enter your enterprise credentials to access the portal",
      fontSize: 11,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 3,
    },
    // Email Input
    {
      id: `login-input1-bg-${ts}`,
      name: "Email Input Field",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 165,
      width: 376,
      height: 44,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#cbd5e1",
      strokeWidth: 1,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 4,
    },
    {
      id: `login-input1-txt-${ts}`,
      name: "Email Placeholder",
      type: "text",
      x: baseX + 46,
      y: baseY + 178,
      width: 348,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "✉ corporate.email@transvolt.in",
      fontSize: 12,
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 5,
    },
    // Password Input
    {
      id: `login-input2-bg-${ts}`,
      name: "Password Input Field",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 225,
      width: 376,
      height: 44,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#cbd5e1",
      strokeWidth: 1,
      cornerRadius: 10,
      blendMode: "normal",
      zIndex: 4,
    },
    {
      id: `login-input2-txt-${ts}`,
      name: "Password Placeholder",
      type: "text",
      x: baseX + 46,
      y: baseY + 238,
      width: 348,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "🔒 ••••••••••••••••",
      fontSize: 12,
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 5,
    },
    // Remember & Forgot
    {
      id: `login-aux-${ts}`,
      name: "Remember & Forgot Password",
      type: "text",
      x: baseX + 32,
      y: baseY + 285,
      width: 376,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#64748b",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "☑ Remember this workstation      Forgot password?",
      fontSize: 11,
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 6,
    },
    // Sign In Button
    {
      id: `login-btn-${ts}`,
      name: "Sign In Button",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 320,
      width: 376,
      height: 48,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#44692b",
      strokeWidth: 1,
      cornerRadius: 12,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(84, 130, 53, 0.35)",
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 5,
      zIndex: 7,
    },
    {
      id: `login-btn-txt-${ts}`,
      name: "Sign In Text",
      type: "text",
      x: baseX + 48,
      y: baseY + 333,
      width: 344,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Sign In to Portal →",
      fontSize: 13,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 8,
    },
  ]
}

export function buildPricingTable(baseX: number = 140, baseY: number = 120): CanvasObject[] {
  const ts = Date.now()
  return [
    // Header
    {
      id: `pr-hdr-${ts}`,
      name: "Pricing Header",
      type: "text",
      x: baseX,
      y: baseY,
      width: 780,
      height: 36,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Enterprise Fleet Telemetry Plans",
      fontSize: 24,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 1,
    },
    // 3 Cards: Starter, Professional, Enterprise
    ...["Starter · ₹4,999/mo", "Professional · ₹12,999/mo (POPULAR)", "Enterprise · Custom"].map((title, i) => {
      const isPop = i === 1
      const cx = baseX + i * 270
      return {
        id: `pr-card-${i}-${ts}`,
        name: `Pricing Tier ${i + 1}`,
        type: "rectangle" as const,
        x: cx,
        y: baseY + 60,
        width: 250,
        height: 360,
        rotation: 0,
        opacity: 1,
        fill: isPop ? "#0f172a" : "#ffffff",
        stroke: isPop ? "#548235" : "#e2e8f0",
        strokeWidth: isPop ? 2.5 : 1,
        cornerRadius: 16,
        blendMode: "normal" as const,
        shadowEnabled: true,
        shadowColor: isPop ? "rgba(84, 130, 53, 0.3)" : "rgba(0,0,0,0.06)",
        shadowBlur: 20,
        shadowOffsetX: 0,
        shadowOffsetY: 8,
        zIndex: 2,
      }
    }),
  ]
}

export function buildNavigationBar(baseX: number = 120, baseY: number = 80): CanvasObject[] {
  const ts = Date.now()
  return [
    {
      id: `nav-bar-${ts}`,
      name: "Navigation Bar Frame",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 800,
      height: 64,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#e2e8f0",
      strokeWidth: 1,
      cornerRadius: 14,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.08)",
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      zIndex: 1,
    },
    {
      id: `nav-brand-${ts}`,
      name: "Brand Logo Title",
      type: "text",
      x: baseX + 28,
      y: baseY + 18,
      width: 180,
      height: 28,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡ TRANSVOLT",
      fontSize: 16,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: `nav-links-${ts}`,
      name: "Nav Links",
      type: "text",
      x: baseX + 240,
      y: baseY + 22,
      width: 360,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#475569",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Fleet Vehicles   ·   Depot Charging   ·   Telematics   ·   About",
      fontSize: 12,
      fontWeight: "500",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 2,
    },
    {
      id: `nav-cta-${ts}`,
      name: "Navbar Action Button",
      type: "rectangle",
      x: baseX + 640,
      y: baseY + 14,
      width: 135,
      height: 36,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#44692b",
      strokeWidth: 1,
      cornerRadius: 8,
      blendMode: "normal",
      zIndex: 3,
    },
    {
      id: `nav-cta-txt-${ts}`,
      name: "Navbar Action Text",
      type: "text",
      x: baseX + 645,
      y: baseY + 22,
      width: 125,
      height: 20,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Contact Us →",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 4,
    },
  ]
}

export function buildAnalyticsChart(baseX: number = 200, baseY: number = 120): CanvasObject[] {
  const ts = Date.now()
  return [
    {
      id: `chart-bg-${ts}`,
      name: "Analytics Chart Card",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 540,
      height: 360,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#1e293b",
      strokeWidth: 1.5,
      cornerRadius: 20,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.35)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 8,
      zIndex: 1,
    },
    {
      id: `chart-title-${ts}`,
      name: "Chart Title",
      type: "text",
      x: baseX + 32,
      y: baseY + 26,
      width: 476,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "Depot Energy Usage & Fleet Throughput (MWh)",
      fontSize: 14,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 2,
    },
    // 6 Bar Graph Columns
    ...[40, 75, 110, 85, 140, 160].map((h, idx) => ({
      id: `bar-${idx}-${ts}`,
      name: `Bar ${idx + 1}`,
      type: "rectangle" as const,
      x: baseX + 50 + idx * 72,
      y: baseY + 270 - h,
      width: 44,
      height: h,
      rotation: 0,
      opacity: 1,
      fill: idx === 5 ? "#10b981" : "#548235",
      stroke: "#334155",
      strokeWidth: 1,
      cornerRadius: 6,
      blendMode: "normal" as const,
      zIndex: 3,
    })),
  ]
}

/**
 * Universal Concept Synthesizer
 * Devises a complete multi-node design for ANY arbitrary prompt provided by the user
 */
export function buildConceptIllustration(
  conceptName: string,
  baseX: number = 200,
  baseY: number = 120
): CanvasObject[] {
  const ts = Date.now()
  const cleanName = conceptName
    .replace(/^(create|draw|make|design|build|add|generate)\s+(a|an|the)?/i, "")
    .trim()
  const displayTitle = cleanName ? cleanName.toUpperCase() : "CUSTOM VECTOR COMPONENT"

  return [
    // Outer Presentation Frame
    {
      id: `concept-frame-${ts}`,
      name: `${displayTitle} Frame`,
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 560,
      height: 380,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#334155",
      strokeWidth: 1.5,
      cornerRadius: 20,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.35)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // Top Metadata Pill
    {
      id: `concept-pill-${ts}`,
      name: "Concept Category Pill",
      type: "rectangle",
      x: baseX + 32,
      y: baseY + 28,
      width: 220,
      height: 28,
      rotation: 0,
      opacity: 1,
      fill: "rgba(84, 130, 53, 0.2)",
      stroke: "#548235",
      strokeWidth: 1,
      cornerRadius: 999,
      blendMode: "normal",
      zIndex: 2,
    },
    {
      id: `concept-pill-txt-${ts}`,
      name: "Pill Label",
      type: "text",
      x: baseX + 40,
      y: baseY + 34,
      width: 204,
      height: 18,
      rotation: 0,
      opacity: 1,
      fill: "#86efac",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "⚡ EVA ARCHITECT SYNTHESIS",
      fontSize: 10,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 3,
    },
    // Central Primary Vector Subject
    {
      id: `concept-hero-shape-${ts}`,
      name: `${displayTitle} Core Geometry`,
      type: "rectangle",
      x: baseX + 190,
      y: baseY + 85,
      width: 180,
      height: 140,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#548235",
      strokeWidth: 3,
      cornerRadius: 18,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(84, 130, 53, 0.4)",
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 6,
      zIndex: 4,
    },
    // Inner Geometric Focal Motif
    {
      id: `concept-motif-${ts}`,
      name: "Focal Geometric Motif",
      type: "shape",
      subtype: "star",
      x: baseX + 245,
      y: baseY + 120,
      width: 70,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "#eab308",
      stroke: "#ca8a04",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 5,
    },
    // Display Headline
    {
      id: `concept-title-${ts}`,
      name: "Concept Title Text",
      type: "text",
      x: baseX + 32,
      y: baseY + 250,
      width: 496,
      height: 36,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: displayTitle,
      fontSize: 22,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 6,
    },
    // Subtitle Description
    {
      id: `concept-sub-${ts}`,
      name: "Concept Subtitle",
      type: "text",
      x: baseX + 32,
      y: baseY + 295,
      width: 496,
      height: 44,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: `Engineered by Eva Design Tool · Production-ready vector hierarchy & scalable layout specs.`,
      fontSize: 12,
      fontWeight: "normal",
      fontFamily: "Poppins",
      textAlign: "center",
      lineHeight: 1.4,
      zIndex: 7,
    },
  ]
}

// ─────────────────────────────────────────────────────────────────────────────
// Real-World Visual Generators: House, Car, Logo, Phone, Nature
// ─────────────────────────────────────────────────────────────────────────────

export function buildModernHouseIllustration(baseX: number = 180, baseY: number = 100): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Sky & Landscape Canvas Plate
    {
      id: `house-plate-${ts}`,
      name: "Landscape Canvas Plate",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 720,
      height: 480,
      rotation: 0,
      opacity: 1,
      fill: "#0b1329",
      stroke: "#1e293b",
      strokeWidth: 2,
      cornerRadius: 24,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.5)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
      zIndex: 1,
    },
    // 2. Warm Sun / Ambient Horizon
    {
      id: `house-sun-${ts}`,
      name: "Ambient Horizon Glow",
      type: "circle",
      x: baseX + 80,
      y: baseY + 50,
      width: 80,
      height: 80,
      rotation: 0,
      opacity: 0.9,
      fill: "#f59e0b",
      stroke: "#fbbf24",
      strokeWidth: 2,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(245, 158, 11, 0.4)",
      shadowBlur: 30,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      zIndex: 2,
    },
    // 3. Ground Lawn Base (Transvolt Green)
    {
      id: `house-lawn-${ts}`,
      name: "Manicured Green Lawn",
      type: "rectangle",
      x: baseX + 20,
      y: baseY + 390,
      width: 680,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "#15803d",
      stroke: "#166534",
      strokeWidth: 2,
      cornerRadius: 12,
      blendMode: "normal",
      zIndex: 3,
    },
    // 4. Main House Structural Body (Two-Story Modern Villa)
    {
      id: `house-body-${ts}`,
      name: "Villa Structural Facade",
      type: "rectangle",
      x: baseX + 200,
      y: baseY + 170,
      width: 380,
      height: 230,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#334155",
      strokeWidth: 2,
      cornerRadius: 4,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.3)",
      shadowBlur: 16,
      shadowOffsetX: 4,
      shadowOffsetY: 8,
      zIndex: 4,
    },
    // 5. Modern Angled Pitched Roof
    {
      id: `house-roof-${ts}`,
      name: "Pitched Architectural Roof",
      type: "shape",
      subtype: "triangle",
      x: baseX + 160,
      y: baseY + 80,
      width: 460,
      height: 100,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#0f172a",
      strokeWidth: 3,
      blendMode: "normal",
      zIndex: 5,
    },
    // 6. Rooftop Chimney
    {
      id: `house-chimney-${ts}`,
      name: "Stone Chimney Stack",
      type: "rectangle",
      x: baseX + 510,
      y: baseY + 90,
      width: 36,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "#475569",
      stroke: "#1e293b",
      strokeWidth: 2,
      cornerRadius: 2,
      blendMode: "normal",
      zIndex: 4,
    },
    // 7. Second Floor Panoramic Balcony Window
    {
      id: `house-win-top-${ts}`,
      name: "Upper Master Suite Window",
      type: "rectangle",
      x: baseX + 240,
      y: baseY + 195,
      width: 140,
      height: 75,
      rotation: 0,
      opacity: 0.95,
      fill: "#38bdf8",
      stroke: "#0284c7",
      strokeWidth: 2,
      cornerRadius: 4,
      blendMode: "normal",
      zIndex: 6,
    },
    // 8. Ground Floor Living Glass Window
    {
      id: `house-win-bot-${ts}`,
      name: "Living Room Glass Bay",
      type: "rectangle",
      x: baseX + 240,
      y: baseY + 300,
      width: 140,
      height: 85,
      rotation: 0,
      opacity: 0.95,
      fill: "#60a5fa",
      stroke: "#2563eb",
      strokeWidth: 2,
      cornerRadius: 4,
      blendMode: "normal",
      zIndex: 6,
    },
    // 9. Modern Front Entrance Porch Overhang
    {
      id: `house-porch-${ts}`,
      name: "Entrance Porch Overhang",
      type: "rectangle",
      x: baseX + 420,
      y: baseY + 270,
      width: 110,
      height: 14,
      rotation: 0,
      opacity: 1,
      fill: "#334155",
      stroke: "#0f172a",
      strokeWidth: 1.5,
      cornerRadius: 2,
      blendMode: "normal",
      zIndex: 6,
    },
    // 10. Front Entrance Door (Transvolt Accent)
    {
      id: `house-door-${ts}`,
      name: "Solid Oak Front Door",
      type: "rectangle",
      x: baseX + 435,
      y: baseY + 285,
      width: 75,
      height: 115,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#365314",
      strokeWidth: 2,
      cornerRadius: 4,
      blendMode: "normal",
      zIndex: 7,
    },
    // 11. Metallic Door Handle
    {
      id: `house-handle-${ts}`,
      name: "Brass Door Hardware",
      type: "circle",
      x: baseX + 495,
      y: baseY + 345,
      width: 8,
      height: 8,
      rotation: 0,
      opacity: 1,
      fill: "#fef08a",
      stroke: "#ca8a04",
      strokeWidth: 1,
      blendMode: "normal",
      zIndex: 8,
    },
    // 12. Garden Pathway Paving Stones
    {
      id: `house-path-${ts}`,
      name: "Entrance Stone Pathway",
      type: "rectangle",
      x: baseX + 435,
      y: baseY + 400,
      width: 75,
      height: 50,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#64748b",
      strokeWidth: 1.5,
      cornerRadius: 4,
      blendMode: "normal",
      zIndex: 5,
    },
    // 13. Decorative Garden Pine Tree (Left)
    {
      id: `house-tree-trunk-${ts}`,
      name: "Pine Tree Trunk",
      type: "rectangle",
      x: baseX + 105,
      y: baseY + 330,
      width: 18,
      height: 70,
      rotation: 0,
      opacity: 1,
      fill: "#78350f",
      stroke: "#451a03",
      strokeWidth: 1.5,
      cornerRadius: 2,
      blendMode: "normal",
      zIndex: 4,
    },
    {
      id: `house-tree-foliage-${ts}`,
      name: "Evergreen Foliage Canopy",
      type: "shape",
      subtype: "triangle",
      x: baseX + 65,
      y: baseY + 200,
      width: 100,
      height: 140,
      rotation: 0,
      opacity: 1,
      fill: "#16a34a",
      stroke: "#14532d",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 5,
    },
    // 14. Title & Specification Banner
    {
      id: `house-title-${ts}`,
      name: "House Title Label",
      type: "text",
      x: baseX + 30,
      y: baseY + 20,
      width: 660,
      height: 30,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "MODERN ARCHITECTURAL RESIDENCE · ELEVATION VIEW",
      fontSize: 14,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 10,
    },
  ]
}

export function buildModernCarIllustration(
  baseX: number = 180,
  baseY: number = 140,
  rawPrompt: string = ""
): CanvasObject[] {
  const ts = Date.now()
  const lower = rawPrompt.toLowerCase()
  let bodyColor = "#dc2626" // Sleek sports red
  let strokeColor = "#991b1b"
  let shadowColor = "rgba(220, 38, 38, 0.4)"

  if (lower.includes("green") || lower.includes("transvolt")) {
    bodyColor = "#548235"
    strokeColor = "#365314"
    shadowColor = "rgba(84, 130, 53, 0.4)"
  } else if (lower.includes("orange")) {
    bodyColor = "#ea580c"
    strokeColor = "#c2410c"
    shadowColor = "rgba(234, 88, 12, 0.4)"
  } else if (lower.includes("blue")) {
    bodyColor = "#2563eb"
    strokeColor = "#1d4ed8"
    shadowColor = "rgba(37, 99, 235, 0.4)"
  } else if (lower.includes("yellow")) {
    bodyColor = "#eab308"
    strokeColor = "#ca8a04"
    shadowColor = "rgba(234, 179, 8, 0.4)"
  } else if (lower.includes("black")) {
    bodyColor = "#18181b"
    strokeColor = "#27272a"
    shadowColor = "rgba(0, 0, 0, 0.5)"
  }

  return [
    // 1. Stage Backdrop Container
    {
      id: `car-bg-${ts}`,
      name: "Automotive Stage Plate",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 720,
      height: 420,
      rotation: 0,
      opacity: 1,
      fill: "#090d16",
      stroke: "#1e293b",
      strokeWidth: 2,
      cornerRadius: 24,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.5)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // 2. Asphalt Road Base
    {
      id: `car-road-${ts}`,
      name: "Speedway Surface",
      type: "rectangle",
      x: baseX + 30,
      y: baseY + 330,
      width: 660,
      height: 50,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#334155",
      strokeWidth: 2,
      cornerRadius: 8,
      blendMode: "normal",
      zIndex: 2,
    },
    // 3. Main Car Body Chassis
    {
      id: `car-body-${ts}`,
      name: "Aerodynamic Vehicle Chassis",
      type: "rectangle",
      x: baseX + 100,
      y: baseY + 220,
      width: 520,
      height: 100,
      rotation: 0,
      opacity: 1,
      fill: bodyColor,
      stroke: strokeColor,
      strokeWidth: 3,
      cornerRadius: 24,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor,
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 8,
      zIndex: 4,
    },
    // 4. Cabin Glass Dome / Windshield
    {
      id: `car-cabin-${ts}`,
      name: "Panoramic Cabin Canopy",
      type: "rectangle",
      x: baseX + 200,
      y: baseY + 155,
      width: 300,
      height: 75,
      rotation: 0,
      opacity: 0.95,
      fill: "#0f172a",
      stroke: "#38bdf8",
      strokeWidth: 2,
      cornerRadius: 20,
      blendMode: "normal",
      zIndex: 5,
    },
    // 5. Cabin Windows Glass Panels
    {
      id: `car-win-front-${ts}`,
      name: "Front Windshield Glass",
      type: "rectangle",
      x: baseX + 220,
      y: baseY + 168,
      width: 120,
      height: 55,
      rotation: 0,
      opacity: 0.9,
      fill: "#38bdf8",
      stroke: "#0284c7",
      strokeWidth: 1.5,
      cornerRadius: 8,
      blendMode: "normal",
      zIndex: 6,
    },
    {
      id: `car-win-rear-${ts}`,
      name: "Rear Cabin Glass",
      type: "rectangle",
      x: baseX + 355,
      y: baseY + 168,
      width: 125,
      height: 55,
      rotation: 0,
      opacity: 0.9,
      fill: "#38bdf8",
      stroke: "#0284c7",
      strokeWidth: 1.5,
      cornerRadius: 8,
      blendMode: "normal",
      zIndex: 6,
    },
    // 6. Front Wheel (Tire + Alloy Rim)
    {
      id: `car-tire-front-${ts}`,
      name: "Front Performance Tire",
      type: "circle",
      x: baseX + 160,
      y: baseY + 285,
      width: 85,
      height: 85,
      rotation: 0,
      opacity: 1,
      fill: "#020617",
      stroke: "#475569",
      strokeWidth: 5,
      blendMode: "normal",
      zIndex: 7,
    },
    {
      id: `car-rim-front-${ts}`,
      name: "Front Alloy Rim",
      type: "circle",
      x: baseX + 180,
      y: baseY + 305,
      width: 45,
      height: 45,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#cbd5e1",
      strokeWidth: 3,
      blendMode: "normal",
      zIndex: 8,
    },
    // 7. Rear Wheel (Tire + Alloy Rim)
    {
      id: `car-tire-rear-${ts}`,
      name: "Rear Performance Tire",
      type: "circle",
      x: baseX + 475,
      y: baseY + 285,
      width: 85,
      height: 85,
      rotation: 0,
      opacity: 1,
      fill: "#020617",
      stroke: "#475569",
      strokeWidth: 5,
      blendMode: "normal",
      zIndex: 7,
    },
    {
      id: `car-rim-rear-${ts}`,
      name: "Rear Alloy Rim",
      type: "circle",
      x: baseX + 495,
      y: baseY + 305,
      width: 45,
      height: 45,
      rotation: 0,
      opacity: 1,
      fill: "#94a3b8",
      stroke: "#cbd5e1",
      strokeWidth: 3,
      blendMode: "normal",
      zIndex: 8,
    },
    // 8. LED Headlight
    {
      id: `car-headlight-${ts}`,
      name: "LED Matrix Headlamp",
      type: "rectangle",
      x: baseX + 100,
      y: baseY + 235,
      width: 32,
      height: 18,
      rotation: 0,
      opacity: 1,
      fill: "#fef08a",
      stroke: "#eab308",
      strokeWidth: 1.5,
      cornerRadius: 6,
      blendMode: "normal",
      zIndex: 7,
    },
    // 9. Rear LED Taillight
    {
      id: `car-taillight-${ts}`,
      name: "Aero Rear Taillamp",
      type: "rectangle",
      x: baseX + 590,
      y: baseY + 235,
      width: 28,
      height: 16,
      rotation: 0,
      opacity: 1,
      fill: "#ef4444",
      stroke: "#b91c1c",
      strokeWidth: 1.5,
      cornerRadius: 6,
      blendMode: "normal",
      zIndex: 7,
    },
    // 10. Title Badge
    {
      id: `car-title-${ts}`,
      name: "Vehicle Title",
      type: "text",
      x: baseX + 30,
      y: baseY + 30,
      width: 660,
      height: 32,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "TRANSVOLT HYPER-EV · AERODYNAMIC SPORTS COUPE",
      fontSize: 16,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 10,
    },
  ]
}

export function buildBrandLogoIllustration(baseX: number = 220, baseY: number = 130): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Logo Backdrop Badge
    {
      id: `logo-bg-${ts}`,
      name: "Logo Container Badge",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 560,
      height: 380,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#334155",
      strokeWidth: 2,
      cornerRadius: 28,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.5)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 12,
      zIndex: 1,
    },
    // 2. Geometric Hexagonal Emblem
    {
      id: `logo-emblem-${ts}`,
      name: "Brand Geometric Prism",
      type: "shape",
      subtype: "hexagon",
      x: baseX + 225,
      y: baseY + 50,
      width: 110,
      height: 110,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#86efac",
      strokeWidth: 3,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(84, 130, 53, 0.5)",
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 6,
      zIndex: 3,
    },
    // 3. Inner Center Star Accent
    {
      id: `logo-star-${ts}`,
      name: "Core Energy Spark",
      type: "shape",
      subtype: "star",
      x: baseX + 255,
      y: baseY + 80,
      width: 50,
      height: 50,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#e2e8f0",
      strokeWidth: 1.5,
      blendMode: "normal",
      zIndex: 4,
    },
    // 4. Primary Brand Name
    {
      id: `logo-name-${ts}`,
      name: "Brand Identity Name",
      type: "text",
      x: baseX + 40,
      y: baseY + 195,
      width: 480,
      height: 48,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "TRANSVOLT",
      fontSize: 38,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "center",
      letterSpacing: 4,
      zIndex: 5,
    },
    // 5. Brand Tagline Hierarchy
    {
      id: `logo-tagline-${ts}`,
      name: "Brand Sub-Tagline",
      type: "text",
      x: baseX + 40,
      y: baseY + 255,
      width: 480,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#86efac",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "CLEAN MOBILITY · ELECTRIC TRANSIT SYSTEMS",
      fontSize: 12,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      letterSpacing: 2,
      zIndex: 6,
    },
    // 6. Registered Trademark Pill
    {
      id: `logo-pill-${ts}`,
      name: "Verification Badge",
      type: "rectangle",
      x: baseX + 215,
      y: baseY + 300,
      width: 130,
      height: 26,
      rotation: 0,
      opacity: 1,
      fill: "rgba(84, 130, 53, 0.2)",
      stroke: "#548235",
      strokeWidth: 1,
      cornerRadius: 999,
      blendMode: "normal",
      zIndex: 7,
    },
    {
      id: `logo-pill-txt-${ts}`,
      name: "Verification Badge Text",
      type: "text",
      x: baseX + 220,
      y: baseY + 305,
      width: 120,
      height: 18,
      rotation: 0,
      opacity: 1,
      fill: "#86efac",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "OFFICIAL IDENTITY",
      fontSize: 9,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "center",
      zIndex: 8,
    },
  ]
}

export function buildSmartphoneDeviceIllustration(baseX: number = 240, baseY: number = 80): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Phone Titanium Outer Chassis
    {
      id: `phone-chassis-${ts}`,
      name: "Smartphone Bezel Frame",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 320,
      height: 520,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#334155",
      strokeWidth: 4,
      cornerRadius: 42,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.6)",
      shadowBlur: 32,
      shadowOffsetX: 0,
      shadowOffsetY: 16,
      zIndex: 1,
    },
    // 2. Edge-to-Edge OLED Screen
    {
      id: `phone-screen-${ts}`,
      name: "OLED Retina Display",
      type: "rectangle",
      x: baseX + 14,
      y: baseY + 14,
      width: 292,
      height: 492,
      rotation: 0,
      opacity: 1,
      fill: "#020617",
      stroke: "#1e293b",
      strokeWidth: 1,
      cornerRadius: 32,
      blendMode: "normal",
      zIndex: 2,
    },
    // 3. Dynamic Island Notch
    {
      id: `phone-notch-${ts}`,
      name: "Dynamic Island Pill",
      type: "rectangle",
      x: baseX + 115,
      y: baseY + 26,
      width: 90,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#000000",
      stroke: "#1e293b",
      strokeWidth: 1,
      cornerRadius: 999,
      blendMode: "normal",
      zIndex: 5,
    },
    // 4. Status Bar Time & 5G
    {
      id: `phone-time-${ts}`,
      name: "Status Bar Time",
      type: "text",
      x: baseX + 32,
      y: baseY + 30,
      width: 70,
      height: 18,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "9:41 AM",
      fontSize: 11,
      fontWeight: "700",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 5,
    },
    // 5. Featured App Card
    {
      id: `phone-card-${ts}`,
      name: "Fleet Health App Card",
      type: "rectangle",
      x: baseX + 30,
      y: baseY + 80,
      width: 260,
      height: 160,
      rotation: 0,
      opacity: 1,
      fill: "rgba(84, 130, 53, 0.2)",
      stroke: "#548235",
      strokeWidth: 1.5,
      cornerRadius: 20,
      blendMode: "normal",
      zIndex: 4,
    },
    {
      id: `phone-card-title-${ts}`,
      name: "App Card Header",
      type: "text",
      x: baseX + 45,
      y: baseY + 98,
      width: 230,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#86efac",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "TRANSVOLT MOBILE OS",
      fontSize: 12,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 6,
    },
    {
      id: `phone-card-stat-${ts}`,
      name: "Battery Status",
      type: "text",
      x: baseX + 45,
      y: baseY + 130,
      width: 230,
      height: 38,
      rotation: 0,
      opacity: 1,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "98% Charged",
      fontSize: 22,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 6,
    },
    // 6. Home Navigation Pill Bar
    {
      id: `phone-dock-${ts}`,
      name: "Home Navigation Indicator",
      type: "rectangle",
      x: baseX + 105,
      y: baseY + 488,
      width: 110,
      height: 5,
      rotation: 0,
      opacity: 0.8,
      fill: "#ffffff",
      stroke: "#000000",
      strokeWidth: 0,
      cornerRadius: 999,
      blendMode: "normal",
      zIndex: 6,
    },
  ]
}

export function buildTreeNatureIllustration(baseX: number = 220, baseY: number = 100): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Nature Horizon Plate
    {
      id: `tree-bg-${ts}`,
      name: "Nature Backdrop Plate",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 600,
      height: 460,
      rotation: 0,
      opacity: 1,
      fill: "#064e3b",
      stroke: "#047857",
      strokeWidth: 2,
      cornerRadius: 24,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.4)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // 2. Sunlight Glow
    {
      id: `tree-sun-${ts}`,
      name: "Golden Sunlight",
      type: "circle",
      x: baseX + 90,
      y: baseY + 50,
      width: 70,
      height: 70,
      rotation: 0,
      opacity: 0.85,
      fill: "#fef08a",
      stroke: "#fde047",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 2,
    },
    // 3. Ground Soil Mound
    {
      id: `tree-ground-${ts}`,
      name: "Organic Soil Layer",
      type: "rectangle",
      x: baseX + 30,
      y: baseY + 380,
      width: 540,
      height: 60,
      rotation: 0,
      opacity: 1,
      fill: "#022c22",
      stroke: "#064e3b",
      strokeWidth: 2,
      cornerRadius: 12,
      blendMode: "normal",
      zIndex: 3,
    },
    // 4. Tree Trunk Base
    {
      id: `tree-trunk-${ts}`,
      name: "Solid Oak Trunk",
      type: "rectangle",
      x: baseX + 280,
      y: baseY + 260,
      width: 40,
      height: 130,
      rotation: 0,
      opacity: 1,
      fill: "#78350f",
      stroke: "#451a03",
      strokeWidth: 2,
      cornerRadius: 4,
      blendMode: "normal",
      zIndex: 4,
    },
    // 5. Tier 1 Lower Foliage Canopy
    {
      id: `tree-tier-1-${ts}`,
      name: "Lower Foliage Canopy",
      type: "circle",
      x: baseX + 190,
      y: baseY + 180,
      width: 220,
      height: 140,
      rotation: 0,
      opacity: 0.95,
      fill: "#15803d",
      stroke: "#166534",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 5,
    },
    // 6. Tier 2 Upper Foliage Canopy (Bright Emerald)
    {
      id: `tree-tier-2-${ts}`,
      name: "Crown Foliage Canopy",
      type: "circle",
      x: baseX + 215,
      y: baseY + 110,
      width: 170,
      height: 120,
      rotation: 0,
      opacity: 0.95,
      fill: "#22c55e",
      stroke: "#16a34a",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 6,
    },
    // 7. Title Label
    {
      id: `tree-title-${ts}`,
      name: "Nature Title",
      type: "text",
      x: baseX + 30,
      y: baseY + 20,
      width: 540,
      height: 28,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "ECOSYSTEM CONSERVATION · SUSTAINABLE NATURE",
      fontSize: 13,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 7,
    },
  ]
}

export function buildRobotAIIllustration(baseX: number = 220, baseY: number = 100): CanvasObject[] {
  const ts = Date.now()
  return [
    // 1. Cybernetic Lab Stage
    {
      id: `bot-bg-${ts}`,
      name: "Cybernetic Plate",
      type: "rectangle",
      x: baseX,
      y: baseY,
      width: 580,
      height: 460,
      rotation: 0,
      opacity: 1,
      fill: "#030712",
      stroke: "#1f2937",
      strokeWidth: 2,
      cornerRadius: 24,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(0,0,0,0.6)",
      shadowBlur: 24,
      shadowOffsetX: 0,
      shadowOffsetY: 10,
      zIndex: 1,
    },
    // 2. Robot Torso Chassis
    {
      id: `bot-torso-${ts}`,
      name: "Armored Torso Chassis",
      type: "rectangle",
      x: baseX + 205,
      y: baseY + 230,
      width: 170,
      height: 160,
      rotation: 0,
      opacity: 1,
      fill: "#1e293b",
      stroke: "#38bdf8",
      strokeWidth: 2,
      cornerRadius: 20,
      blendMode: "normal",
      zIndex: 3,
    },
    // 3. Glowing Arc Core Reactor
    {
      id: `bot-core-${ts}`,
      name: "Power Arc Core",
      type: "circle",
      x: baseX + 260,
      y: baseY + 280,
      width: 60,
      height: 60,
      rotation: 0,
      opacity: 1,
      fill: "#548235",
      stroke: "#86efac",
      strokeWidth: 3,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(84, 130, 53, 0.6)",
      shadowBlur: 20,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      zIndex: 4,
    },
    // 4. Robot Head Visor
    {
      id: `bot-head-${ts}`,
      name: "Head Chassis",
      type: "rectangle",
      x: baseX + 225,
      y: baseY + 110,
      width: 130,
      height: 95,
      rotation: 0,
      opacity: 1,
      fill: "#0f172a",
      stroke: "#64748b",
      strokeWidth: 2,
      cornerRadius: 16,
      blendMode: "normal",
      zIndex: 5,
    },
    // 5. Neon Visor Eyes
    {
      id: `bot-visor-${ts}`,
      name: "Neon Scanner Visor",
      type: "rectangle",
      x: baseX + 245,
      y: baseY + 140,
      width: 90,
      height: 24,
      rotation: 0,
      opacity: 1,
      fill: "#38bdf8",
      stroke: "#0284c7",
      strokeWidth: 2,
      cornerRadius: 999,
      blendMode: "normal",
      shadowEnabled: true,
      shadowColor: "rgba(56, 189, 248, 0.6)",
      shadowBlur: 16,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      zIndex: 6,
    },
    // 6. Antenna Beacon
    {
      id: `bot-antenna-${ts}`,
      name: "Antenna Transmitter",
      type: "rectangle",
      x: baseX + 285,
      y: baseY + 75,
      width: 10,
      height: 35,
      rotation: 0,
      opacity: 1,
      fill: "#64748b",
      stroke: "#475569",
      strokeWidth: 1,
      cornerRadius: 2,
      blendMode: "normal",
      zIndex: 4,
    },
    {
      id: `bot-beacon-${ts}`,
      name: "Beacon Light",
      type: "circle",
      x: baseX + 283,
      y: baseY + 63,
      width: 14,
      height: 14,
      rotation: 0,
      opacity: 1,
      fill: "#22c55e",
      stroke: "#16a34a",
      strokeWidth: 2,
      blendMode: "normal",
      zIndex: 5,
    },
    // 7. Title Label
    {
      id: `bot-title-${ts}`,
      name: "Bot Label",
      type: "text",
      x: baseX + 30,
      y: baseY + 20,
      width: 520,
      height: 28,
      rotation: 0,
      opacity: 1,
      fill: "#f8fafc",
      stroke: "#000000",
      strokeWidth: 0,
      blendMode: "normal",
      text: "EVA AGENTIC ARCHITECT · CYBERNETIC CO-PILOT",
      fontSize: 13,
      fontWeight: "800",
      fontFamily: "Poppins",
      textAlign: "left",
      zIndex: 7,
    },
  ]
}

export function buildArchitecturalDesign(
  archetypeKey: string,
  baseX: number = 200,
  baseY: number = 100,
  rawPrompt: string = ""
): CanvasObject[] {
  switch (archetypeKey) {
    case "house":
      return buildModernHouseIllustration(baseX, baseY)
    case "house_blueprint":
      return buildHouseBlueprint(baseX, baseY)
    case "car_vehicle":
      return buildModernCarIllustration(baseX, baseY, rawPrompt)
    case "vehicle_bus":
      return buildVehicleBus(baseX, baseY)
    case "logo_design":
      return buildBrandLogoIllustration(baseX, baseY)
    case "smartphone_device":
      return buildSmartphoneDeviceIllustration(baseX, baseY)
    case "tree_nature":
      return buildTreeNatureIllustration(baseX, baseY)
    case "robot_ai":
      return buildRobotAIIllustration(baseX, baseY)
    case "landing_page_hero":
      return buildLandingPageHero(baseX, baseY)
    case "checkout_screen":
      return buildCheckoutScreen(baseX, baseY)
    case "ats_resume":
      return buildModernATSResume(baseX, baseY)
    case "greeting_card":
    case "wedding_invitation":
      return buildGreetingCard(baseX, baseY)
    case "login_screen":
      return buildLoginScreen(baseX, baseY)
    case "pricing_table":
      return buildPricingTable(baseX, baseY)
    case "navigation_bar":
      return buildNavigationBar(baseX, baseY)
    case "analytics_chart":
      return buildAnalyticsChart(baseX, baseY)
    case "fintech_dashboard":
    case "corporate_brochure":
    case "luxury_packaging":
    case "social_media_poster":
      return buildFintechDashboardCard(baseX, baseY)
    default:
      return buildConceptIllustration(rawPrompt || archetypeKey, baseX, baseY)
  }
}
